SCOPES = ["https://www.googleapis.com/auth/spreadsheets"]
SPREADSHEET_ID = "1_NdtVkGrwzdqNms2D5xIDiR18QC6gubPBZJshauDKLo"
SHEET_NAME = "customers"
CREDS_FILE = "service_account.json"
SECRET_KEY = "ecopurify-secret-key"
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
PERMANENT_SESSION_LIFETIME = 60 * 60 * 6  # 6 hours